[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.0",
    "gensim>=4.3.3",
    "numpy>=1.26.4",
    "requests>=2.32.3",
    "tensorflow>=2.18.1",
    "werkzeug>=3.1.3",
]
